version: '3'

networks:
  my-network:
    driver: bridge

services:

  gateway:
    container_name: gateway
    image: complexjava/api-gateway
    ports:
      - 7000:7000
    environment:
      EUREKA_URL: //discovery:8761
    networks:
      - my-network


  data:
    image: complex-java/video-data
    container_name: data
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      MYSQL_HOST: repository:${database_port}/${database_name}
      BROKER_URL: activemq:${broker_port}
      EUREKA_URL: //discovery:8761
    networks:
      - my-network


  uploader:
    image: complexjava/video-uploader
    container_name: uploader
    ports:
      - 8082:8082
    volumes:
      - .${file_location}:/videos
    environment:
      FILE_LOCATION: ${file_location}
      BROKER_URL: activemq:${broker_port}
      EUREKA_URL: //discovery:8761
    networks:
      - my-network


  encoder:
    image: complex-java/encoder-image2201
    container_name: encoder
    user: root
    volumes:
      - .${file_location}:/videos
    ports:
      - 8083:8083
    environment:
       BROKER_URL: activemq:${broker_port}
       FILE_LOCATION: ${file_location}
       EUREKA_URL: //discovery:8761
    networks:
      - my-network


  activemq:
    image: rmohr/activemq
    container_name: activemq
    restart: always
    ports:
      - 8161:8161
    expose:
      - ${broker_port}
    networks:
      - my-network
