---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-repository
  labels:
    app: mysql-repository
spec:
  selector:
    matchLabels:
      app: mysql-repository
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-repository
        #tier: backend
    spec:
      containers:
      - name: mysql-repository
        image: mysql
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'root'
        - name: MYSQL_DATABASE
          value: streamingApp
        - name: MYSQL_PORT
          value: '3306'
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-repository
spec:
  selector:
    app: mysql-repository

  ports:
    - protocol: TCP
      port: 3306
  type: ClusterIP
